name: Test

on:
  # Trigger the workflow on push to the main branch
  push:
    branches:
      - main

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: yarn

      # ESLint and Prettier must be in `package.json`
      - name: Install dependencies
        id: install
        run: yarn install --immutable --check-cache

      - name: Run unit tests
        id: lint
        run: yarn test:ci

      - name: Update Coverage Badge
        id: coverage-badge
        # GitHub actions: default branch variable
        # https://stackoverflow.com/questions/64781462/github-actions-default-branch-variable
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: we-cli/coverage-badge-action@main
